/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 24.05.2026 12:45:58

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 10128;
#else
constexpr int kTensorArenaSize = 9104;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,3960 } };
const TfArray<1, float> quant0_scale = { 1, { 0.0034313725773245096, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 99, 40, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 99, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 50, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 50, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 400, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[4] = { 727, 838, -1478, -9, };
const TfArray<1, float> quant6_scale = { 1, { 7.5195290264673531e-05, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[4*400] = { 
  20, 6, 5, -17, 29, -15, -13, -18, -9, -8, -2, -19, -35, 38, 27, -42, 45, -22, -68, -35, 14, -29, 0, -2, -6, -6, 12, 36, 8, 24, 41, -27, 34, 21, -63, -36, -26, 1, 22, 14, -2, -34, -19, 18, 45, 9, 63, -55, 29, -11, -66, -95, -10, 3, -33, 2, -73, -34, -39, -25, -15, 45, 57, 28, 83, -8, -4, -7, 4, 25, -11, 19, -34, -33, -50, -27, -27, 61, 42, 18, 17, 48, 0, -13, 31, 36, -16, 23, -6, 12, 15, -20, 22, 44, -3, 23, 17, 29, -10, -26, -17, 38, -51, -16, -51, -37, -77, -67, -37, 44, -11, 68, -23, 36, -5, -39, 10, 36, -65, -18, -12, -4, -25, -79, -42, 52, -25, 28, -40, 35, 10, -29, -32, 17, -60, 16, -8, 7, -34, -31, -19, 23, -54, 45, 30, 39, -28, -72, -40, 59, -72, -29, -54, -24, -84, -70, -40, 14, -12, 54, 55, 38, -11, -39, 26, 20, -68, 49, -101, -30, -79, -61, -72, 53, 40, 58, 80, 30, -50, -79, 4, 47, -50, 77, -28, 20, -11, -64, 23, 80, 42, 12, 38, 32, -33, -71, -103, 37, -18, 39, -37, 14, -25, 16, 17, 63, 43, -13, 32, 42, -111, -69, -23, 79, -32, 8, -69, -72, -91, -14, -15, 44, 33, -5, 52, 60, -101, -109, -49, 68, -47, 6, -78, -58, -78, 0, -34, 53, 20, 39, 62, 71, 26, -4, 4, 36, -39, 62, -31, -7, -56, 16, -5, 23, 6, -7, 23, 17, 30, -8, -16, 44, -68, 29, -41, 0, 8, 4, 41, 53, 4, 12, 38, 17, 14, -18, 10, 13, 12, 53, -22, 17, 17, -34, 3, 10, 11, 22, 23, 25, 8, -20, -44, 14, -3, 14, 17, 2, -1, 21, 47, 5, -32, 24, 26, 13, 16, -7, -17, 31, 18, 70, 21, -9, 0, -34, 1, 29, 14, 25, 29, -1, -14, -34, -17, 34, 36, 57, 0, -5, 25, 1, 21, -15, 28, -26, -20, 21, 19, 21, 3, -14, -27, 10, -12, -16, -23, 33, 53, 4, 22, -28, 38, 49, -38, -24, 33, 30, 23, 39, 6, -30, -10, -24, 1, 36, -2, 12, 43, -13, -78, -71, -38, 14, -29, 37, -24, -58, -68, -18, 12, 14, 28, -14, 2, -9, -10, -43, -34, -8, 3, 36, -12, -18, -58, 35, 21, 3, 22, -4, 
  52, 34, 35, -16, -6, -34, 46, 44, 36, 47, 55, -28, 60, 4, -8, 91, 25, 19, 28, 51, -19, -9, -7, 8, 5, -13, -37, -5, -42, 37, 1, 20, -44, -39, -12, -23, 29, -30, -54, -6, -24, 14, 9, 7, -10, 41, -88, -9, 26, 36, 74, 73, -8, -46, 0, 6, 16, 14, 0, -6, -66, 2, -52, 68, -60, -34, -54, -73, -35, -48, -13, -53, -39, -6, 22, -55, 51, 25, -59, 11, -51, -68, -55, -35, -32, -78, -82, -16, -37, -27, -85, -67, -110, 19, -68, 1, -44, -16, 31, -8, 23, -24, -45, -9, -5, 37, 14, -60, -73, 4, -44, 25, -36, -5, 26, 52, 3, -23, 0, 3, 4, 34, 48, -6, 4, 30, -61, 27, -49, 9, 17, 32, 41, -24, 9, -56, 8, 25, 36, -28, 4, -7, -66, 23, -93, -32, 48, 55, 39, 5, -33, -46, -2, -6, 17, -17, -14, -18, -56, 13, -46, -52, -40, -34, -10, -49, -38, -36, -50, -34, -32, -47, -60, -36, -24, -27, -65, -58, -68, -79, -25, -32, -51, -54, -40, -11, -102, -30, -37, -10, -85, 2, -27, -57, -5, -53, 60, -47, -24, -3, -25, -38, -37, -28, -55, 24, -39, 60, -31, -73, 31, 22, -26, -45, -22, -11, 16, 26, 7, -38, -37, 32, -15, 29, -37, -27, 55, 45, 27, -57, 17, -10, 16, 14, 28, -20, -34, 1, -28, 56, 0, -36, 29, 49, 11, -18, 24, 7, -27, -12, 17, -26, -23, 21, 10, 61, 3, -26, 0, 7, 13, -62, 30, -41, -5, 16, 17, 27, 44, 47, -8, 56, -1, -11, -8, 9, -21, -14, 10, -48, -12, -5, -1, -12, -9, 16, 19, 87, -20, -23, -27, -56, -32, -48, -31, -24, -55, -16, -60, -15, -80, 37, -16, 86, -25, -40, -26, -39, -45, -24, -23, -25, -65, -10, -67, -57, -72, 60, 0, 67, -4, -22, -45, -47, -24, -1, -62, -24, -39, -23, -40, -43, -88, 71, 4, 62, 13, -17, -25, -87, -22, -38, -44, -3, -44, -31, -37, -31, -45, 29, 15, 90, -15, -22, -18, -70, -43, -30, -38, -4, -39, -19, -45, -44, -46, 48, 0, 63, 36, -7, -48, -91, -48, -36, -57, 10, -43, -45, -82, -12, -74, 58, 40, 72, 37, 31, -46, -98, 13, 5, -71, 10, -50, -56, -81, -40, -71, 52, 4, 107, 
  1, 5, -27, -25, -17, -34, 48, 11, 14, -14, -2, 41, -11, -11, 37, -2, 14, -35, -68, -5, -1, -3, 28, -32, -7, -35, -38, 30, -28, -45, 10, -32, 20, -7, 8, 2, 5, -33, 37, 17, 13, -14, -15, 34, -8, -50, 22, -34, 82, -28, -31, -26, 23, -12, 33, 5, 44, 11, 26, 32, 31, -26, 64, -81, 89, -33, -69, -54, -33, -13, 97, 9, 8, 10, 45, 68, 26, -85, 105, -72, 52, -56, -67, 10, -61, -19, 86, -15, 11, 16, 30, 79, 37, -104, 103, -111, 68, -44, -37, 21, -16, -50, 54, 30, 29, 20, 11, 65, 45, -70, 92, -66, 91, -19, -76, -37, -37, -29, 67, -1, 42, -28, 25, 37, 62, -72, 63, -57, 65, -39, -16, -19, -10, -2, 54, -20, 1, -18, -12, 28, -8, -44, 59, -34, 51, -56, -64, -2, -21, -14, 54, 22, 29, -5, 27, 45, 29, -86, 59, -94, -16, -57, -41, 15, -23, -5, 70, 2, 25, 13, 33, 21, 40, -84, 64, -98, 23, -47, -52, -21, -6, -56, 61, -16, 0, 11, 48, 33, 39, -59, 8, -87, -3, 7, -31, 17, 28, 0, 14, 0, 39, -10, 12, 51, 5, -36, 20, -64, 8, -47, -33, -23, -13, -25, 0, -44, -10, 22, -21, 0, 10, -45, -11, -63, -49, -63, -18, -13, -18, -27, -17, -47, -2, -36, 6, -12, 3, -55, -7, -33, -48, -11, 7, -23, -53, -22, 11, -39, -7, 6, -17, 17, 12, -88, -47, -56, 13, -18, -47, -10, 15, 8, 32, -16, 29, -16, 7, 20, -3, -47, 6, -77, 12, -17, -27, -6, -3, 4, 62, -7, 30, 5, 16, 22, 46, -62, 47, -74, 12, -34, -48, -2, -35, -41, 25, -23, 10, 34, 15, 37, 24, -105, 31, -86, -18, -45, -38, -30, 3, -28, 36, -22, 21, -17, 9, 49, 67, -56, 4, -82, -21, -55, 16, -12, 29, -53, 19, -3, 15, 34, 3, -2, 1, -59, -8, -82, -64, -23, 2, 28, -2, -33, 59, -30, 10, 17, 35, 23, 39, -65, 43, -79, 7, -34, -12, 52, -20, -21, 60, 4, 42, 6, 6, 65, 24, -61, -28, -58, -7, 4, -48, -8, 8, -53, -24, -48, 35, -21, -17, 33, 16, -53, 15, -72, -25, -21, -36, 0, -61, 3, -9, 6, -27, -19, 14, -24, 17, -47, 10, -91, 
  -79, -12, -12, 15, -4, 0, -42, -31, -50, -75, -39, 6, -71, -18, -20, -14, -45, 10, 10, 46, 21, 2, -23, -1, 11, 3, 39, -55, -25, 35, -74, -9, -20, 20, 26, -7, 20, 1, -47, -28, -14, 17, -12, -46, -34, 8, -52, 41, -69, 22, 31, 34, 4, 27, -50, -37, 19, 18, 12, -56, -35, -13, -112, -28, -98, 32, 63, 50, -13, 38, -61, -4, 3, 45, 30, -24, -67, -24, -127, -35, -60, 35, 37, 66, 34, 26, -44, 8, 26, 31, 4, -46, -47, -25, -84, -35, -50, 2, 8, 2, -23, -1, -17, -29, 13, 24, 37, -13, 15, 3, -27, -32, 5, -32, -34, 3, 6, -32, -8, -6, -10, -7, -1, 22, 4, -38, -7, -51, 24, 4, -20, -5, -13, -9, 24, -4, 13, 20, 14, 19, 10, -17, 17, -6, 48, -16, 42, 78, 9, 27, 41, 36, 31, 10, 52, 7, -19, -23, -3, -16, -37, 8, 74, 47, -23, 30, 15, -10, 55, 51, 57, 32, 68, -50, 11, -11, 21, 50, 72, 72, 33, 52, 7, -30, 45, -6, 6, 39, 30, 7, -34, 18, -13, -22, 63, 28, 2, 19, 12, -18, 35, 26, 12, -45, -30, -31, -38, -18, -13, -25, 21, 42, 19, 4, -1, 40, 29, 55, 25, -27, -9, -19, -25, -9, -26, 19, 21, 59, -8, -16, 15, 26, 30, 61, 69, 11, 22, -16, -41, -18, -21, -23, -35, 15, -18, 9, -10, -21, -12, 19, 22, 19, 24, -2, 21, -29, -8, 33, -5, -10, 16, -1, 6, 24, -16, 34, -22, -12, -27, -31, -32, -44, -41, -18, 16, -15, 4, 23, -47, 25, -38, 9, -1, -36, 6, -17, -26, -29, -53, 14, 31, -13, 35, -8, -21, 14, -12, 0, 22, -30, -30, 35, -13, -46, -6, 14, 27, 27, -5, 20, -6, 32, 15, 9, 24, 11, -7, -37, -32, 14, -6, 20, 30, -2, 10, 27, -19, -4, -4, 23, 28, -21, -2, 18, -70, -4, 28, 26, 26, -24, -21, 16, -23, 25, -33, 17, -12, -16, -12, 13, -49, 25, -27, -17, 33, 2, -7, 11, -10, 39, 41, 24, 37, -36, -24, -19, -30, -49, -35, 36, 83, 102, 44, -1, 14, 3, 42, 68, 31, 21, 33, -8, -29, -23, -9, 21, 59, 86, 33, -16, -22, -7, 45, 62, 40, 30, 40, -64, -36, -30, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 4,400 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0042425594292581081, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { -1031, -1210, -1162, 202, -2014, -1433, -407, -1276, -903, -887, -616, 83, -259, 1451, -318, 2630, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 3.7555731978500262e-05, 3.7465440982487053e-05, 4.4926018745172769e-05, 4.7980014642234892e-05, 3.2892799936234951e-05, 4.0527793316869065e-05, 3.5210196074331179e-05, 3.7024543416919187e-05, 4.5261011109687388e-05, 4.6881454181857407e-05, 5.1808980060741305e-05, 3.7963185604894534e-05, 5.145261820871383e-05, 5.5778760724933818e-05, 4.1016246541403234e-05, 7.0211834099609405e-05, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ 83,109,121,82,-56,-3,-38,-46, 91,103,80,1,-69,13,127,-126, 30,115,66,68,-78,-26,63,-61, 
  /* [1][0][][] */ -55,127,28,19,29,-35,-31,72, -29,43,24,-19,105,96,9,115, 14,76,98,-41,-33,-28,-32,15, 
  /* [2][0][][] */ -73,-6,-27,-4,70,-33,10,89, 40,-16,0,24,127,-62,16,126, -75,-9,8,-20,42,-12,78,68, 
  /* [3][0][][] */ -57,-39,5,-7,127,4,1,72, -64,-56,-42,56,95,-23,7,69, -104,-15,4,-8,91,-41,98,69, 
  /* [4][0][][] */ -48,-55,-78,-62,-42,-68,7,48, -83,-30,-92,-37,62,25,41,54, 7,34,-2,-9,-73,43,96,127, 
  /* [5][0][][] */ -61,109,111,10,46,-29,-58,126, -39,97,42,-24,102,121,-85,31, -27,127,89,13,56,60,-49,85, 
  /* [6][0][][] */ 72,-14,0,127,-102,-16,44,-57, -30,-34,-5,1,-41,15,53,-35, -19,-52,-10,120,-43,18,1,-112, 
  /* [7][0][][] */ -10,127,70,-80,-93,79,13,-31, 85,122,79,61,-16,55,113,21, 12,57,-17,-6,28,26,68,15, 
  /* [8][0][][] */ 37,-47,10,69,81,-9,112,61, -94,-53,-51,68,127,-2,30,91, -68,-24,6,68,73,28,35,0, 
  /* [9][0][][] */ 71,-36,7,35,30,38,127,70, -53,-15,-23,-39,87,31,25,59, -34,-17,-13,42,48,18,21,82, 
  /* [10][0][][] */ 14,-30,-21,43,76,-15,127,17, -105,-43,-15,16,58,-32,16,42, -96,-15,0,54,22,26,16,77, 
  /* [11][0][][] */ -50,20,-36,127,83,17,5,-93, -19,-9,-12,35,76,-62,-11,-34, -16,11,2,79,-96,-70,-38,-73, 
  /* [12][0][][] */ 24,31,-53,117,45,28,127,16, 5,18,-60,21,-14,59,-62,-21, -8,42,31,57,-15,-31,-39,1, 
  /* [13][0][][] */ 84,34,48,-23,-48,30,-38,21, 85,70,34,-16,-55,-43,-36,5, 87,50,127,-11,25,-46,-26,77, 
  /* [14][0][][] */ 36,62,68,28,-42,18,3,-90, 2,97,57,72,-13,-23,-8,-113, 43,-12,26,127,-6,-78,-10,-100, 
  /* [15][0][][] */ 127,46,66,-23,-9,-47,-43,53, 59,14,86,-13,-25,-57,22,36, 74,-24,98,-28,-55,-38,2,47, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0039036101661622524, 0.0038942252285778522, 0.0046696909703314304, 0.0049871290102601051, 0.0034189368598163128, 0.0042125317268073559, 0.003659810870885849, 0.0038483974058181047, 0.0047045107930898666, 0.0048729423433542252, 0.0053851185366511345, 0.003945961594581604, 0.0053480775095522404, 0.0057977447286248207, 0.0042633023113012314, 0.0072979438118636608, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { 116, 8779, -688, 7638, 4481, 40308, 1093, 9919, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 1.307046568399528e-05, 8.1886510088224895e-06, 1.1558574442460667e-05, 9.2550499175558798e-06, 1.2809383406420238e-05, 6.8779572757193819e-06, 1.3587001376436092e-05, 9.3834460130892694e-06, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*40] = { 
  /* [0][0][][] */ 19,30,-28,-59,-85,-44,-3,-39,-17,-10,75,-77,45,-66,-66,-1,-34,-66,-37,-112,-73,-84,-58,-24,21,1,36,-29,27,-46,-48,6,-21,-61,-42,-99,-65,-68,11,114, 43,64,-11,38,9,-1,69,41,37,27,124,51,-21,57,63,60,49,30,8,39,-55,33,41,32,52,50,127,68,115,55,28,93,9,-1,3,10,42,33,-3,105, -26,-48,-7,-99,17,-82,-47,-31,7,84,49,-50,49,-49,-52,-5,-59,-39,61,-64,-43,-89,-29,17,78,31,41,53,25,18,3,-51,-15,-53,-74,-97,-100,5,7,98, 
  /* [1][0][][] */ -92,-99,-53,13,-98,105,-60,86,-18,-28,-39,-82,83,-65,127,55,-48,-19,81,85,39,-10,72,8,8,-104,-119,-59,-37,36,43,-64,-14,35,9,54,-26,-64,-7,-28, 30,-45,-94,-19,-11,118,84,78,-4,-63,-29,-50,66,-75,-28,89,44,-49,-45,-27,42,118,-7,-26,-93,-57,-35,-63,-7,95,19,25,13,79,-3,-4,3,-6,-5,-44, 42,-100,-39,-107,-103,87,84,16,-106,-2,-89,25,97,-58,26,36,13,72,68,-37,-49,45,-47,25,28,42,-90,54,-25,-44,78,-19,34,-103,-68,57,79,0,-65,73, 
  /* [2][0][][] */ 13,29,-83,-66,-56,-7,49,53,-38,44,50,-29,77,-82,10,72,68,-24,58,37,44,25,12,-34,-22,-127,-107,-116,-76,-60,-9,24,-66,1,28,-12,87,-18,3,9, -15,-47,-50,-86,2,50,41,-16,58,-33,89,-38,-4,-7,107,60,-22,-5,50,53,4,85,4,-32,-72,-8,-76,-34,-91,-48,19,59,-71,-39,-48,-18,-25,63,-48,0, -24,-104,-96,-66,28,20,59,60,31,-47,-47,-21,21,3,34,47,-27,-23,78,-62,11,41,-32,-15,2,-110,-40,-84,-24,47,58,-30,-42,-122,-10,-49,23,60,-59,-30, 
  /* [3][0][][] */ -125,-75,-57,-102,40,-94,43,15,70,-107,-78,-80,-49,50,-13,13,93,70,65,7,77,73,15,96,49,123,114,-44,73,20,40,69,47,32,55,55,-15,23,-64,24, -126,-101,-71,-75,-17,-38,57,-23,54,-17,-127,-41,-71,-22,30,-27,87,103,33,30,84,42,-42,105,17,0,90,-45,17,-42,61,88,16,-16,-29,-21,-5,-42,66,-72, -12,-73,-8,-116,-7,-18,20,15,-68,-44,-9,-94,-108,46,-106,26,31,49,11,67,-29,51,-88,54,-23,52,101,21,61,-78,59,-38,-25,-20,-37,1,10,-71,-79,-77, 
  /* [4][0][][] */ -14,-74,-56,21,-90,-14,-35,3,-63,-43,-63,60,-5,-7,-51,5,-51,-39,-59,-54,-29,-59,-49,-25,-63,-64,-29,36,40,-5,-23,13,-33,-30,51,26,53,127,38,33, 2,-25,12,-58,-57,-37,-5,-92,-32,-74,-23,56,-36,-5,-79,-20,-33,10,7,-20,-9,16,18,20,-26,-20,-4,8,23,71,-28,57,-38,-42,78,103,56,104,22,29, 36,-70,-52,-24,-47,-22,-23,-40,-75,-70,-9,81,27,23,-67,14,-28,-36,-5,24,21,-5,-12,-42,-18,-101,-62,9,11,76,54,-33,69,34,4,119,120,117,49,-35, 
  /* [5][0][][] */ -56,-5,-33,22,51,23,-64,15,9,72,-47,99,21,51,-50,-7,-95,28,-7,81,-48,-28,78,-123,-35,-118,-11,8,-94,72,-127,65,-5,-43,56,4,-51,-85,58,-34, -107,-122,27,49,25,-43,-88,-65,-82,-67,-93,-81,-29,37,-70,-26,-20,-29,72,85,59,-68,27,40,-101,6,-102,39,12,15,-65,-36,-95,28,-79,-36,6,68,-48,-84, 52,-105,70,-26,21,17,-18,-28,40,87,48,37,-25,54,-75,27,72,-59,-8,-113,51,70,-84,15,-51,-84,54,41,9,-54,-5,69,-44,-118,-83,-89,-36,-90,26,96, 
  /* [6][0][][] */ -71,-56,-100,-37,-52,-60,-64,-106,-124,-105,-97,-44,-106,-77,-76,-41,-39,32,22,13,-17,-3,-41,-16,-61,-54,13,-11,-14,-59,-53,-93,-20,-68,-49,25,-42,31,-56,-87, -23,-52,22,7,-28,59,36,21,-14,34,-23,44,-43,57,62,22,54,38,111,115,57,-1,16,24,-19,78,36,64,15,19,69,72,4,79,19,104,127,102,24,19, -44,-76,-82,-26,-65,-56,-16,-24,30,30,-37,-26,-3,-9,-20,-5,101,21,65,38,53,-20,27,1,24,12,-37,-1,-8,31,-39,-10,-10,36,-1,76,-4,-29,-36,-12, 
  /* [7][0][][] */ -31,-81,-38,20,66,-3,-66,19,-87,-52,28,-78,-22,-127,-91,-45,-60,42,-58,-46,-31,-11,-95,-34,37,-20,19,85,73,69,15,9,72,119,59,-12,54,2,41,-67, -94,-56,-93,-24,-8,-29,11,20,-65,0,27,-81,-31,-78,-127,-98,-108,-59,-28,-93,-25,-24,11,17,-7,-24,-5,73,48,-16,-22,41,76,84,123,62,46,53,-6,-24, -43,-84,-79,5,20,-7,-19,-23,-87,37,-33,13,-124,-29,-33,11,-6,33,29,-25,-14,8,25,46,-56,75,54,91,4,64,79,113,-27,36,8,62,-46,-35,34,-25, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,40 } };
const TfArray<8, float> quant11_scale = { 8, { 0.0038091070018708706, 0.0023864067625254393, 0.003368498757481575, 0.0026971860788762569, 0.0037330202758312225, 0.0020044331904500723, 0.0039596403948962688, 0.0027346042916178703, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,99,40 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,99,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.0096207689493894577, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,99,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,50,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,50,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,50,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.017724039033055305, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,50,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,400 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,4 } };
const TfArray<1, float> quant21_scale = { 1, { 0.17261777818202972, } };
const TfArray<1, int> quant21_zero = { 1, { 6 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfArray<1, float> quant22_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension0, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 1600, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension13, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension15, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension17, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension19, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_982734_6_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_982734_6_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_982734_6_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_982734_6_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_982734_6_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
